import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

import { describe, expect, it } from "vitest"

/**
 * Guards the local deltas in a vendored shadcn component.
 *
 * `select.tsx` is generated by `shadcn add`, and re-running the CLI rewrites
 * it wholesale. Every fix applied to it is therefore one command away from
 * disappearing, and none of it would fail a typecheck or a lint — the class
 * strings are opaque literals. That is not a hypothetical: each assertion below
 * corresponds to a defect that shipped, was found in review, and would return
 * silently on the next regeneration.
 *
 * These read the source rather than the rendered output on purpose. What is
 * being defended is the file's content against an overwrite, and asserting on
 * a real render would need a DOM the repository otherwise has no use for.
 */

const source = readFileSync(
  fileURLToPath(new URL("./select.tsx", import.meta.url)),
  "utf8"
)

/** The class string of one component, so an assertion cannot match another's. */
function classesOf(component: string): string {
  const start = source.indexOf(`function ${component}(`)
  expect(start, `${component} is gone from select.tsx`).toBeGreaterThan(-1)

  const next = source.indexOf("\nfunction ", start + 1)
  return source.slice(start, next === -1 ? source.length : next)
}

describe("select.tsx local deltas", () => {
  it("documents every deviation at the top of the file", () => {
    // Condition 1 of the rule in CLAUDE.md: without the block, the next person
    // to regenerate has no way to know anything was changed.
    expect(source).toContain("DELIBERATE DEVIATIONS")
  })

  /**
   * Upstream pairs `line-clamp-1` with `flex` on the same element. The flex
   * rule is emitted later at equal specificity, so `-webkit-line-clamp` never
   * runs: a clipped label loses its ellipsis and is cut mid-word.
   */
  it("truncates the trigger's value with an ellipsis", () => {
    const trigger = classesOf("SelectTrigger")

    expect(trigger).toContain("*:data-[slot=select-value]:truncate")
    expect(trigger).not.toContain("line-clamp-1")
    expect(classesOf("SelectValue")).toContain("truncate")
  })

  /** A `w-fit` trigger is as wide as whatever is selected in it. */
  it("keeps the trigger's width independent of the selected option", () => {
    const trigger = classesOf("SelectTrigger")

    expect(trigger).toContain("w-full")
    expect(trigger).not.toContain("w-fit")
  })

  /**
   * `anywhere` is the only `overflow-wrap` value that feeds min-content sizing,
   * which is what lets a long label shrink inside the item. `wrap-break-word`
   * would restore the overflow and the popup would slice it under the check.
   */
  it("lets a long option wrap instead of overflowing the popup", () => {
    const item = classesOf("SelectItem")

    expect(item).toContain("wrap-anywhere")
    expect(item).not.toContain("whitespace-nowrap")
  })

  /**
   * The check indicator is absolutely positioned with no `top`, so its position
   * follows the item's `align-items`. `items-start` moved it off centre on
   * every single-line option while moving the text nowhere at all.
   */
  it("centres the check indicator against its label", () => {
    // Anchored to its neighbours: a bare `items-center` also matches the
    // `*:[span]:last:items-center` variant further along the same string, which
    // would let a reverted `items-start` slip through.
    expect(classesOf("SelectItem")).toMatch(/cursor-default items-center gap-2/)
  })

  /** Without it the first and last rows sit flush against a 16px radius. */
  it("keeps the popup's inner padding", () => {
    expect(classesOf("SelectContent")).toContain("p-1")
  })
})
